paths:
  # renamed from zarr_store to match your specification
  initial_condition: "/scratch4/NAGAPE/epic/Wei.Huang/src/h3/utils/google-graphcast-grid/init_20000701T00.nc"
  graph_dir: "/scratch4/NAGAPE/epic/Wei.Huang/src/h3/utils/google-graphcast-grid"

model_params:
  hierarchy_levels: [4, 2, 0]
  history_steps: 2
  latent_dim: 128
  processor_layers: 4
  learning_rate: 0.0002

inference_params:
  weights: "checkpoints/epoch14-ckpt"
  start_time: "2000-07-01T00:00:00"
  steps: 12
  output: "icosahedral_forecast_20000701T00.nc"
